// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// FedorovWynnAlgorithm_Rcpp
Rcpp::List FedorovWynnAlgorithm_Rcpp(Rcpp::List protocols, IntegerVector ndimen, IntegerVector nbprot, IntegerVector numprot, NumericVector freq, IntegerVector nbdata, NumericVector vectps, NumericVector fisher, IntegerVector error, IntegerVector protdep, NumericVector freqdep, bool show_process, double delta);
RcppExport SEXP _PFIM_FedorovWynnAlgorithm_Rcpp(SEXP protocolsSEXP, SEXP ndimenSEXP, SEXP nbprotSEXP, SEXP numprotSEXP, SEXP freqSEXP, SEXP nbdataSEXP, SEXP vectpsSEXP, SEXP fisherSEXP, SEXP errorSEXP, SEXP protdepSEXP, SEXP freqdepSEXP, SEXP show_processSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type protocols(protocolsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ndimen(ndimenSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nbprot(nbprotSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type numprot(numprotSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type freq(freqSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nbdata(nbdataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vectps(vectpsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type fisher(fisherSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type error(errorSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type protdep(protdepSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type freqdep(freqdepSEXP);
    Rcpp::traits::input_parameter< bool >::type show_process(show_processSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(FedorovWynnAlgorithm_Rcpp(protocols, ndimen, nbprot, numprot, freq, nbdata, vectps, fisher, error, protdep, freqdep, show_process, delta));
    return rcpp_result_gen;
END_RCPP
}
// MultiplicativeAlgorithm_Rcpp
Rcpp::List MultiplicativeAlgorithm_Rcpp(Rcpp::List fisherMatrices, int n_fim, arma::vec weights, int p, double lambda, double delta, int iteration_init, bool show_process);
RcppExport SEXP _PFIM_MultiplicativeAlgorithm_Rcpp(SEXP fisherMatricesSEXP, SEXP n_fimSEXP, SEXP weightsSEXP, SEXP pSEXP, SEXP lambdaSEXP, SEXP deltaSEXP, SEXP iteration_initSEXP, SEXP show_processSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type fisherMatrices(fisherMatricesSEXP);
    Rcpp::traits::input_parameter< int >::type n_fim(n_fimSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< int >::type iteration_init(iteration_initSEXP);
    Rcpp::traits::input_parameter< bool >::type show_process(show_processSEXP);
    rcpp_result_gen = Rcpp::wrap(MultiplicativeAlgorithm_Rcpp(fisherMatrices, n_fim, weights, p, lambda, delta, iteration_init, show_process));
    return rcpp_result_gen;
END_RCPP
}
// pgbo_optimize_Rcpp
List pgbo_optimize_Rcpp(NumericVector initial_pos, List sorting_groups, int max_iteration, int N, double mute_effect, int purge_iteration, double fit_base, int max_attempts, double cauchy_prob, bool show_process, Function eval_d, Function check_valid_group, double ftol, int stall_iterations);
RcppExport SEXP _PFIM_pgbo_optimize_Rcpp(SEXP initial_posSEXP, SEXP sorting_groupsSEXP, SEXP max_iterationSEXP, SEXP NSEXP, SEXP mute_effectSEXP, SEXP purge_iterationSEXP, SEXP fit_baseSEXP, SEXP max_attemptsSEXP, SEXP cauchy_probSEXP, SEXP show_processSEXP, SEXP eval_dSEXP, SEXP check_valid_groupSEXP, SEXP ftolSEXP, SEXP stall_iterationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type initial_pos(initial_posSEXP);
    Rcpp::traits::input_parameter< List >::type sorting_groups(sorting_groupsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iteration(max_iterationSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type mute_effect(mute_effectSEXP);
    Rcpp::traits::input_parameter< int >::type purge_iteration(purge_iterationSEXP);
    Rcpp::traits::input_parameter< double >::type fit_base(fit_baseSEXP);
    Rcpp::traits::input_parameter< int >::type max_attempts(max_attemptsSEXP);
    Rcpp::traits::input_parameter< double >::type cauchy_prob(cauchy_probSEXP);
    Rcpp::traits::input_parameter< bool >::type show_process(show_processSEXP);
    Rcpp::traits::input_parameter< Function >::type eval_d(eval_dSEXP);
    Rcpp::traits::input_parameter< Function >::type check_valid_group(check_valid_groupSEXP);
    Rcpp::traits::input_parameter< double >::type ftol(ftolSEXP);
    Rcpp::traits::input_parameter< int >::type stall_iterations(stall_iterationsSEXP);
    rcpp_result_gen = Rcpp::wrap(pgbo_optimize_Rcpp(initial_pos, sorting_groups, max_iteration, N, mute_effect, purge_iteration, fit_base, max_attempts, cauchy_prob, show_process, eval_d, check_valid_group, ftol, stall_iterations));
    return rcpp_result_gen;
END_RCPP
}
// pso_optimize_Rcpp
List pso_optimize_Rcpp(int n_pop_in, int max_iter, arma::rowvec initial_pos, List windows_list, List sorting_groups, double phi1, double phi2, double constriction, bool show_process, Function eval_fitness, Nullable<Function> sample_valid_pos, Nullable<Function> eval_fitness_batch, double ftol, int stall_iterations);
RcppExport SEXP _PFIM_pso_optimize_Rcpp(SEXP n_pop_inSEXP, SEXP max_iterSEXP, SEXP initial_posSEXP, SEXP windows_listSEXP, SEXP sorting_groupsSEXP, SEXP phi1SEXP, SEXP phi2SEXP, SEXP constrictionSEXP, SEXP show_processSEXP, SEXP eval_fitnessSEXP, SEXP sample_valid_posSEXP, SEXP eval_fitness_batchSEXP, SEXP ftolSEXP, SEXP stall_iterationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_pop_in(n_pop_inSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type initial_pos(initial_posSEXP);
    Rcpp::traits::input_parameter< List >::type windows_list(windows_listSEXP);
    Rcpp::traits::input_parameter< List >::type sorting_groups(sorting_groupsSEXP);
    Rcpp::traits::input_parameter< double >::type phi1(phi1SEXP);
    Rcpp::traits::input_parameter< double >::type phi2(phi2SEXP);
    Rcpp::traits::input_parameter< double >::type constriction(constrictionSEXP);
    Rcpp::traits::input_parameter< bool >::type show_process(show_processSEXP);
    Rcpp::traits::input_parameter< Function >::type eval_fitness(eval_fitnessSEXP);
    Rcpp::traits::input_parameter< Nullable<Function> >::type sample_valid_pos(sample_valid_posSEXP);
    Rcpp::traits::input_parameter< Nullable<Function> >::type eval_fitness_batch(eval_fitness_batchSEXP);
    Rcpp::traits::input_parameter< double >::type ftol(ftolSEXP);
    Rcpp::traits::input_parameter< int >::type stall_iterations(stall_iterationsSEXP);
    rcpp_result_gen = Rcpp::wrap(pso_optimize_Rcpp(n_pop_in, max_iter, initial_pos, windows_list, sorting_groups, phi1, phi2, constriction, show_process, eval_fitness, sample_valid_pos, eval_fitness_batch, ftol, stall_iterations));
    return rcpp_result_gen;
END_RCPP
}
// fun_amoeba_Rcpp
List fun_amoeba_Rcpp(NumericMatrix p, NumericVector y, double ftol, int itmax, Function funk, SEXP data, SEXP outcomes, bool show_process);
RcppExport SEXP _PFIM_fun_amoeba_Rcpp(SEXP pSEXP, SEXP ySEXP, SEXP ftolSEXP, SEXP itmaxSEXP, SEXP funkSEXP, SEXP dataSEXP, SEXP outcomesSEXP, SEXP show_processSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type ftol(ftolSEXP);
    Rcpp::traits::input_parameter< int >::type itmax(itmaxSEXP);
    Rcpp::traits::input_parameter< Function >::type funk(funkSEXP);
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type outcomes(outcomesSEXP);
    Rcpp::traits::input_parameter< bool >::type show_process(show_processSEXP);
    rcpp_result_gen = Rcpp::wrap(fun_amoeba_Rcpp(p, y, ftol, itmax, funk, data, outcomes, show_process));
    return rcpp_result_gen;
END_RCPP
}
// chol_inv_Rcpp
arma::mat chol_inv_Rcpp(const arma::mat& V);
RcppExport SEXP _PFIM_chol_inv_Rcpp(SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(chol_inv_Rcpp(V));
    return rcpp_result_gen;
END_RCPP
}
// safe_solve_Rcpp
arma::mat safe_solve_Rcpp(const arma::mat& M);
RcppExport SEXP _PFIM_safe_solve_Rcpp(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(safe_solve_Rcpp(M));
    return rcpp_result_gen;
END_RCPP
}
// computeMFVar_Rcpp
arma::mat computeMFVar_Rcpp(const arma::mat& V_inv, const Rcpp::List& dV_list);
RcppExport SEXP _PFIM_computeMFVar_Rcpp(SEXP V_invSEXP, SEXP dV_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type V_inv(V_invSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type dV_list(dV_listSEXP);
    rcpp_result_gen = Rcpp::wrap(computeMFVar_Rcpp(V_inv, dV_list));
    return rcpp_result_gen;
END_RCPP
}
// computeMFVar_mixed_Rcpp
arma::mat computeMFVar_mixed_Rcpp(const arma::mat& V_inv, const arma::mat& W, const Rcpp::List& dV_full);
RcppExport SEXP _PFIM_computeMFVar_mixed_Rcpp(SEXP V_invSEXP, SEXP WSEXP, SEXP dV_fullSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type V_inv(V_invSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type dV_full(dV_fullSEXP);
    rcpp_result_gen = Rcpp::wrap(computeMFVar_mixed_Rcpp(V_inv, W, dV_full));
    return rcpp_result_gen;
END_RCPP
}
// computePopFimCombo_Rcpp
arma::mat computePopFimCombo_Rcpp(const arma::mat& gradients, const arma::vec& mu_values, const arma::vec& omega_iiv, const arma::vec& gamma, const arma::mat& error_variance, const Rcpp::IntegerVector& occ_col_widths, const Rcpp::List& sigma_derivatives, bool has_iov);
RcppExport SEXP _PFIM_computePopFimCombo_Rcpp(SEXP gradientsSEXP, SEXP mu_valuesSEXP, SEXP omega_iivSEXP, SEXP gammaSEXP, SEXP error_varianceSEXP, SEXP occ_col_widthsSEXP, SEXP sigma_derivativesSEXP, SEXP has_iovSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type gradients(gradientsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu_values(mu_valuesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type omega_iiv(omega_iivSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type error_variance(error_varianceSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type occ_col_widths(occ_col_widthsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type sigma_derivatives(sigma_derivativesSEXP);
    Rcpp::traits::input_parameter< bool >::type has_iov(has_iovSEXP);
    rcpp_result_gen = Rcpp::wrap(computePopFimCombo_Rcpp(gradients, mu_values, omega_iiv, gamma, error_variance, occ_col_widths, sigma_derivatives, has_iov));
    return rcpp_result_gen;
END_RCPP
}
// residualErrorDerivatives_Rcpp
Rcpp::List residualErrorDerivatives_Rcpp(double sigmaInter, double sigmaSlope, bool sigmaInterFixed, bool sigmaSlopeFixed, double cError, const arma::vec& f, int form);
RcppExport SEXP _PFIM_residualErrorDerivatives_Rcpp(SEXP sigmaInterSEXP, SEXP sigmaSlopeSEXP, SEXP sigmaInterFixedSEXP, SEXP sigmaSlopeFixedSEXP, SEXP cErrorSEXP, SEXP fSEXP, SEXP formSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type sigmaInter(sigmaInterSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaSlope(sigmaSlopeSEXP);
    Rcpp::traits::input_parameter< bool >::type sigmaInterFixed(sigmaInterFixedSEXP);
    Rcpp::traits::input_parameter< bool >::type sigmaSlopeFixed(sigmaSlopeFixedSEXP);
    Rcpp::traits::input_parameter< double >::type cError(cErrorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type f(fSEXP);
    Rcpp::traits::input_parameter< int >::type form(formSEXP);
    rcpp_result_gen = Rcpp::wrap(residualErrorDerivatives_Rcpp(sigmaInter, sigmaSlope, sigmaInterFixed, sigmaSlopeFixed, cError, f, form));
    return rcpp_result_gen;
END_RCPP
}
// pfimCacheHash_Rcpp
std::string pfimCacheHash_Rcpp(const Rcpp::CharacterVector& parts);
RcppExport SEXP _PFIM_pfimCacheHash_Rcpp(SEXP partsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type parts(partsSEXP);
    rcpp_result_gen = Rcpp::wrap(pfimCacheHash_Rcpp(parts));
    return rcpp_result_gen;
END_RCPP
}
// pfimEnvCacheKey_Rcpp
std::string pfimEnvCacheKey_Rcpp(const std::string& x);
RcppExport SEXP _PFIM_pfimEnvCacheKey_Rcpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(pfimEnvCacheKey_Rcpp(x));
    return rcpp_result_gen;
END_RCPP
}
// pfimOdeSimTimesCached_Rcpp
Rcpp::NumericVector pfimOdeSimTimesCached_Rcpp(const std::string& cache_key, const Rcpp::NumericVector& raw_samplings, const Rcpp::Nullable<Rcpp::NumericVector>& event_times, bool enabled, int max_entries);
RcppExport SEXP _PFIM_pfimOdeSimTimesCached_Rcpp(SEXP cache_keySEXP, SEXP raw_samplingsSEXP, SEXP event_timesSEXP, SEXP enabledSEXP, SEXP max_entriesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type cache_key(cache_keySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type raw_samplings(raw_samplingsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::NumericVector>& >::type event_times(event_timesSEXP);
    Rcpp::traits::input_parameter< bool >::type enabled(enabledSEXP);
    Rcpp::traits::input_parameter< int >::type max_entries(max_entriesSEXP);
    rcpp_result_gen = Rcpp::wrap(pfimOdeSimTimesCached_Rcpp(cache_key, raw_samplings, event_times, enabled, max_entries));
    return rcpp_result_gen;
END_RCPP
}
// pfimOdeSimTimesCacheClear_Rcpp
void pfimOdeSimTimesCacheClear_Rcpp();
RcppExport SEXP _PFIM_pfimOdeSimTimesCacheClear_Rcpp() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    pfimOdeSimTimesCacheClear_Rcpp();
    return R_NilValue;
END_RCPP
}
// pfimOdeSimTimesCacheSize_Rcpp
int pfimOdeSimTimesCacheSize_Rcpp();
RcppExport SEXP _PFIM_pfimOdeSimTimesCacheSize_Rcpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(pfimOdeSimTimesCacheSize_Rcpp());
    return rcpp_result_gen;
END_RCPP
}
