// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// FedorovWynnAlgorithm_Rcpp
Rcpp::List FedorovWynnAlgorithm_Rcpp(Rcpp::List protocols, IntegerVector ndimen, IntegerVector nbprot, IntegerVector numprot, NumericVector freq, IntegerVector nbdata, NumericVector vectps, NumericVector fisher, IntegerVector error, IntegerVector protdep, NumericVector freqdep, bool show_process);
RcppExport SEXP _PFIM_FedorovWynnAlgorithm_Rcpp(SEXP protocolsSEXP, SEXP ndimenSEXP, SEXP nbprotSEXP, SEXP numprotSEXP, SEXP freqSEXP, SEXP nbdataSEXP, SEXP vectpsSEXP, SEXP fisherSEXP, SEXP errorSEXP, SEXP protdepSEXP, SEXP freqdepSEXP, SEXP show_processSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type protocols(protocolsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ndimen(ndimenSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nbprot(nbprotSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type numprot(numprotSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type freq(freqSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nbdata(nbdataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vectps(vectpsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type fisher(fisherSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type error(errorSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type protdep(protdepSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type freqdep(freqdepSEXP);
    Rcpp::traits::input_parameter< bool >::type show_process(show_processSEXP);
    rcpp_result_gen = Rcpp::wrap(FedorovWynnAlgorithm_Rcpp(protocols, ndimen, nbprot, numprot, freq, nbdata, vectps, fisher, error, protdep, freqdep, show_process));
    return rcpp_result_gen;
END_RCPP
}
// MultiplicativeAlgorithm_Rcpp
Rcpp::List MultiplicativeAlgorithm_Rcpp(Rcpp::List fisherMatrices, int n_fim, arma::vec weights, int p, double lambda, double delta, int iteration_init, bool show_process);
RcppExport SEXP _PFIM_MultiplicativeAlgorithm_Rcpp(SEXP fisherMatricesSEXP, SEXP n_fimSEXP, SEXP weightsSEXP, SEXP pSEXP, SEXP lambdaSEXP, SEXP deltaSEXP, SEXP iteration_initSEXP, SEXP show_processSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type fisherMatrices(fisherMatricesSEXP);
    Rcpp::traits::input_parameter< int >::type n_fim(n_fimSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< int >::type iteration_init(iteration_initSEXP);
    Rcpp::traits::input_parameter< bool >::type show_process(show_processSEXP);
    rcpp_result_gen = Rcpp::wrap(MultiplicativeAlgorithm_Rcpp(fisherMatrices, n_fim, weights, p, lambda, delta, iteration_init, show_process));
    return rcpp_result_gen;
END_RCPP
}
// pgbo_optimize_Rcpp
List pgbo_optimize_Rcpp(NumericVector initial_pos, List sorting_groups, int max_iteration, int N, double mute_effect, int purge_iteration, double fit_base, int max_attempts, bool show_process, Function eval_d, Function check_valid_group);
RcppExport SEXP _PFIM_pgbo_optimize_Rcpp(SEXP initial_posSEXP, SEXP sorting_groupsSEXP, SEXP max_iterationSEXP, SEXP NSEXP, SEXP mute_effectSEXP, SEXP purge_iterationSEXP, SEXP fit_baseSEXP, SEXP max_attemptsSEXP, SEXP show_processSEXP, SEXP eval_dSEXP, SEXP check_valid_groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type initial_pos(initial_posSEXP);
    Rcpp::traits::input_parameter< List >::type sorting_groups(sorting_groupsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iteration(max_iterationSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type mute_effect(mute_effectSEXP);
    Rcpp::traits::input_parameter< int >::type purge_iteration(purge_iterationSEXP);
    Rcpp::traits::input_parameter< double >::type fit_base(fit_baseSEXP);
    Rcpp::traits::input_parameter< int >::type max_attempts(max_attemptsSEXP);
    Rcpp::traits::input_parameter< bool >::type show_process(show_processSEXP);
    Rcpp::traits::input_parameter< Function >::type eval_d(eval_dSEXP);
    Rcpp::traits::input_parameter< Function >::type check_valid_group(check_valid_groupSEXP);
    rcpp_result_gen = Rcpp::wrap(pgbo_optimize_Rcpp(initial_pos, sorting_groups, max_iteration, N, mute_effect, purge_iteration, fit_base, max_attempts, show_process, eval_d, check_valid_group));
    return rcpp_result_gen;
END_RCPP
}
// pso_optimize_Rcpp
List pso_optimize_Rcpp(int n_pop_in, int max_iter, arma::rowvec initial_pos, List windows_list, List sorting_groups, double phi1, double phi2, double constriction, bool show_process, Function eval_fitness, Nullable<Function> sample_valid_pos, Nullable<Function> eval_fitness_batch);
RcppExport SEXP _PFIM_pso_optimize_Rcpp(SEXP n_pop_inSEXP, SEXP max_iterSEXP, SEXP initial_posSEXP, SEXP windows_listSEXP, SEXP sorting_groupsSEXP, SEXP phi1SEXP, SEXP phi2SEXP, SEXP constrictionSEXP, SEXP show_processSEXP, SEXP eval_fitnessSEXP, SEXP sample_valid_posSEXP, SEXP eval_fitness_batchSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_pop_in(n_pop_inSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type initial_pos(initial_posSEXP);
    Rcpp::traits::input_parameter< List >::type windows_list(windows_listSEXP);
    Rcpp::traits::input_parameter< List >::type sorting_groups(sorting_groupsSEXP);
    Rcpp::traits::input_parameter< double >::type phi1(phi1SEXP);
    Rcpp::traits::input_parameter< double >::type phi2(phi2SEXP);
    Rcpp::traits::input_parameter< double >::type constriction(constrictionSEXP);
    Rcpp::traits::input_parameter< bool >::type show_process(show_processSEXP);
    Rcpp::traits::input_parameter< Function >::type eval_fitness(eval_fitnessSEXP);
    Rcpp::traits::input_parameter< Nullable<Function> >::type sample_valid_pos(sample_valid_posSEXP);
    Rcpp::traits::input_parameter< Nullable<Function> >::type eval_fitness_batch(eval_fitness_batchSEXP);
    rcpp_result_gen = Rcpp::wrap(pso_optimize_Rcpp(n_pop_in, max_iter, initial_pos, windows_list, sorting_groups, phi1, phi2, constriction, show_process, eval_fitness, sample_valid_pos, eval_fitness_batch));
    return rcpp_result_gen;
END_RCPP
}
// fun_amoeba_Rcpp
List fun_amoeba_Rcpp(NumericMatrix p, NumericVector y, double ftol, int itmax, Function funk, SEXP data, SEXP outcomes, bool show_process);
RcppExport SEXP _PFIM_fun_amoeba_Rcpp(SEXP pSEXP, SEXP ySEXP, SEXP ftolSEXP, SEXP itmaxSEXP, SEXP funkSEXP, SEXP dataSEXP, SEXP outcomesSEXP, SEXP show_processSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type ftol(ftolSEXP);
    Rcpp::traits::input_parameter< int >::type itmax(itmaxSEXP);
    Rcpp::traits::input_parameter< Function >::type funk(funkSEXP);
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type outcomes(outcomesSEXP);
    Rcpp::traits::input_parameter< bool >::type show_process(show_processSEXP);
    rcpp_result_gen = Rcpp::wrap(fun_amoeba_Rcpp(p, y, ftol, itmax, funk, data, outcomes, show_process));
    return rcpp_result_gen;
END_RCPP
}
