# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FedorovWynnAlgorithm_Rcpp <- function(protocols, ndimen, nbprot, numprot, freq, nbdata, vectps, fisher, error, protdep, freqdep, show_process = FALSE, delta = 1e-4) {
    .Call(`_PFIM_FedorovWynnAlgorithm_Rcpp`, protocols, ndimen, nbprot, numprot, freq, nbdata, vectps, fisher, error, protdep, freqdep, show_process, delta)
}

MultiplicativeAlgorithm_Rcpp <- function(fisherMatrices, n_fim, weights, p, lambda, delta, iteration_init, show_process = FALSE) {
    .Call(`_PFIM_MultiplicativeAlgorithm_Rcpp`, fisherMatrices, n_fim, weights, p, lambda, delta, iteration_init, show_process)
}

pgbo_optimize_Rcpp <- function(initial_pos, sorting_groups, max_iteration, N, mute_effect, purge_iteration, fit_base, max_attempts, cauchy_prob, show_process, eval_d, check_valid_group, ftol = 0.0, stall_iterations = 5L) {
    .Call(`_PFIM_pgbo_optimize_Rcpp`, initial_pos, sorting_groups, max_iteration, N, mute_effect, purge_iteration, fit_base, max_attempts, cauchy_prob, show_process, eval_d, check_valid_group, ftol, stall_iterations)
}

pso_optimize_Rcpp <- function(n_pop_in, max_iter, initial_pos, windows_list, sorting_groups, phi1, phi2, constriction, show_process, eval_fitness, sample_valid_pos = NULL, eval_fitness_batch = NULL, ftol = 0.0, stall_iterations = 5L) {
    .Call(`_PFIM_pso_optimize_Rcpp`, n_pop_in, max_iter, initial_pos, windows_list, sorting_groups, phi1, phi2, constriction, show_process, eval_fitness, sample_valid_pos, eval_fitness_batch, ftol, stall_iterations)
}

fun_amoeba_Rcpp <- function(p, y, ftol, itmax, funk, data, outcomes, show_process) {
    .Call(`_PFIM_fun_amoeba_Rcpp`, p, y, ftol, itmax, funk, data, outcomes, show_process)
}

chol_inv_Rcpp <- function(V) {
    .Call(`_PFIM_chol_inv_Rcpp`, V)
}

safe_solve_Rcpp <- function(M) {
    .Call(`_PFIM_safe_solve_Rcpp`, M)
}

computeMFVar_Rcpp <- function(V_inv, dV_list) {
    .Call(`_PFIM_computeMFVar_Rcpp`, V_inv, dV_list)
}

computeMFVar_mixed_Rcpp <- function(V_inv, W, dV_full) {
    .Call(`_PFIM_computeMFVar_mixed_Rcpp`, V_inv, W, dV_full)
}

computePopFimCombo_Rcpp <- function(gradients, mu_values, omega_iiv, gamma, error_variance, occ_col_widths, sigma_derivatives, has_iov) {
    .Call(`_PFIM_computePopFimCombo_Rcpp`, gradients, mu_values, omega_iiv, gamma, error_variance, occ_col_widths, sigma_derivatives, has_iov)
}

residualErrorDerivatives_Rcpp <- function(sigmaInter, sigmaSlope, sigmaInterFixed, sigmaSlopeFixed, cError, f, form) {
    .Call(`_PFIM_residualErrorDerivatives_Rcpp`, sigmaInter, sigmaSlope, sigmaInterFixed, sigmaSlopeFixed, cError, f, form)
}

pfimCacheHash_Rcpp <- function(parts) {
    .Call(`_PFIM_pfimCacheHash_Rcpp`, parts)
}

pfimEnvCacheKey_Rcpp <- function(x) {
    .Call(`_PFIM_pfimEnvCacheKey_Rcpp`, x)
}

pfimOdeSimTimesCached_Rcpp <- function(cache_key, raw_samplings, event_times, enabled, max_entries = -1L) {
    .Call(`_PFIM_pfimOdeSimTimesCached_Rcpp`, cache_key, raw_samplings, event_times, enabled, max_entries)
}

pfimOdeSimTimesCacheClear_Rcpp <- function() {
    invisible(.Call(`_PFIM_pfimOdeSimTimesCacheClear_Rcpp`))
}

pfimOdeSimTimesCacheSize_Rcpp <- function() {
    .Call(`_PFIM_pfimOdeSimTimesCacheSize_Rcpp`)
}

