# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FedorovWynnAlgorithm_Rcpp <- function(protocols, ndimen, nbprot, numprot, freq, nbdata, vectps, fisher, error, protdep, freqdep, show_process = FALSE) {
    .Call(`_PFIM_FedorovWynnAlgorithm_Rcpp`, protocols, ndimen, nbprot, numprot, freq, nbdata, vectps, fisher, error, protdep, freqdep, show_process)
}

MultiplicativeAlgorithm_Rcpp <- function(fisherMatrices, n_fim, weights, p, lambda, delta, iteration_init, show_process = FALSE) {
    .Call(`_PFIM_MultiplicativeAlgorithm_Rcpp`, fisherMatrices, n_fim, weights, p, lambda, delta, iteration_init, show_process)
}

pgbo_optimize_Rcpp <- function(initial_pos, sorting_groups, max_iteration, N, mute_effect, purge_iteration, fit_base, max_attempts, show_process, eval_d, check_valid_group) {
    .Call(`_PFIM_pgbo_optimize_Rcpp`, initial_pos, sorting_groups, max_iteration, N, mute_effect, purge_iteration, fit_base, max_attempts, show_process, eval_d, check_valid_group)
}

pso_optimize_Rcpp <- function(n_pop_in, max_iter, initial_pos, windows_list, sorting_groups, phi1, phi2, constriction, show_process, eval_fitness, sample_valid_pos = NULL, eval_fitness_batch = NULL) {
    .Call(`_PFIM_pso_optimize_Rcpp`, n_pop_in, max_iter, initial_pos, windows_list, sorting_groups, phi1, phi2, constriction, show_process, eval_fitness, sample_valid_pos, eval_fitness_batch)
}

fun_amoeba_Rcpp <- function(p, y, ftol, itmax, funk, data, outcomes, show_process) {
    .Call(`_PFIM_fun_amoeba_Rcpp`, p, y, ftol, itmax, funk, data, outcomes, show_process)
}

